### ISSUE TITLE
wine-lol could not run due to modify_ldt being banned by flatpak

### ISSUE THREAD

**Issue by alaviss** [flathub/net.lutris.Lutris#85]
**Describe the problem**
The patch for League of Legends in lutris wine [uses the LDT to store data](https://github.com/lutris/wine/commit/44b40987761e90b645852ec23d921a6d9f97227a#diff-a3c4be1949be01939f59bd1326b0e988R2382-R2396). The syscall responsible for this (`modify_ldt`) is however banned by flatpak via [seccomp](https://github.com/flatpak/flatpak/blob/a61f61870e5239832e797418c7f62f6e7d130960/common/flatpak-run.c#L2584), causing wine to not be able to launch any application.

**Is it reproducible with native Lutris?**
No

**Steps to reproduce**
1. Install League of Legends

**Expected behavior**
League of Legends is installed

**Actual behavior**
<details>

```
2019-12-24 07:03:33,926: Runner %s needs to be installed
2019-12-24 07:03:33,933: Getting runner information for wine (version: lutris-lol-4.20-x86_64)
2019-12-24 07:04:01,127: Downloading file 1 of 1

(lutris:2): Gtk-CRITICAL **: 07:04:04.340: gtk_tree_model_get_column_type: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed

(lutris:2): Gtk-CRITICAL **: 07:04:04.340: gtk_combo_box_get_active_id: assertion 'gtk_tree_model_get_column_type (model, column) == G_TYPE_STRING' failed
2019-12-24 07:04:04,347: Creating a win32 prefix in /home/alaviss/Games/league-of-legends-test
2019-12-24 07:04:09,730: Wine prefix creation is taking longer than expected...
2019-12-24 07:04:16,991: No user.reg found after prefix creation. Prefix might not be valid
2019-12-24 07:04:17,206: Creating a win32 prefix in /home/alaviss/Games/league-of-legends-test
2019-12-24 07:04:22,490: Wine prefix creation is taking longer than expected...
2019-12-24 07:04:29,751: No user.reg found after prefix creation. Prefix might not be valid
2019-12-24 07:04:30,076: The game doesn't have an executable
Running /home/alaviss/.var/app/net.lutris.Lutris/data/lutris/runtime/winetricks/winetricks --unattended d3dcompiler_43 d3dx9
ls: cannot access '/home/alaviss/Games/league-of-legends-test/drive_c': No such file or directory
grep: /home/alaviss/Games/league-of-legends-test/*.reg: No such file or directory
------------------------------------------------------
WINEPREFIX INFO:
Drive C:

Registry info:
/home/alaviss/Games/league-of-legends-test/*.reg:
------------------------------------------------------
------------------------------------------------------
/home/alaviss/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-lol-4.20-x86_64/bin/wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message "modify_ldt: Operation not permitted"
------------------------------------------------------
Waiting on children
Exit with returncode 1
2019-12-24 07:04:32,106: Creating a win32 prefix in /home/alaviss/Games/league-of-legends-test
2019-12-24 07:04:37,384: Wine prefix creation is taking longer than expected...
2019-12-24 07:04:44,646: No user.reg found after prefix creation. Prefix might not be valid
Running /home/alaviss/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-lol-4.20-x86_64/bin/wine /home/alaviss/.var/app/net.lutris.Lutris/cache/lutris/installer/league-of-legends/lol_installer/League%20of%20Legends%20installer%20NA.exe
modify_ldt: Operation not permitted
Waiting on children
Exit with returncode -11
```

</details>

**Flatpak info**
`flatpak --version`
```
Flatpak 1.4.3
```

`flatpak --gl-drivers`
```
default
host
```

**Comment by gasinvein** [comment]
Thanks for the report. However, I don't think it's possible to fix this on our side. Is the syscall really essential for the wine build to work?

**Comment by alaviss** [comment]
Yes, I've patched out the ban on modify_ldt in flatpak just to test it.
The solution right now would be to ask flatpak to add a switch to allow modify_ldt.
A better way would be to invent a fix that doesn't require LDT.

**Comment by eszlari** [comment]
@alaviss Consider opening an issue under: https://github.com/flatpak/flatpak/issues

**Comment by TheGreatestJannet** [comment]
Is this still an issue? I'm looking to run league of legends in a sandbox.

**Comment by ilkekaratas** [comment]
Hello! how did you patch out the ban? I am trying to set League on PS4 gentoo but I get this error. Can you please tell?

**Comment by alaviss** [comment]
> Hello! how did you patch out the ban? I am trying to set League on PS4 gentoo but I get this error. Can you please tell?

Removing these lines should do:
https://github.com/flatpak/flatpak/blob/6f86a8ff423a2e7a8e1db70c69612f3fa49ae9d4/common/flatpak-run.c#L2899-L2901

**Comment by YGLAM** [comment]
> 
> 
> > Hello! how did you patch out the ban? I am trying to set League on PS4 gentoo but I get this error. Can you please tell?
> 
> Removing these lines should do:
> https://github.com/flatpak/flatpak/blob/6f86a8ff423a2e7a8e1db70c69612f3fa49ae9d4/common/flatpak-run.c#L2899-L2901

I'm in the same situation, how should I delete these lines I didn't really understand

**Comment by Tank743** [comment]
> > Hello! how did you patch out the ban? I am trying to set League on PS4 gentoo but I get this error. Can you please tell?
> 
> Removing these lines should do: https://github.com/flatpak/flatpak/blob/6f86a8ff423a2e7a8e1db70c69612f3fa49ae9d4/common/flatpak-run.c#L2899-L2901

How do you access the code to remove those lines?

**Comment by alaviss** [comment]
> > > Hello! how did you patch out the ban? I am trying to set League on PS4 gentoo but I get this error. Can you please tell?
> > 
> > 
> > Removing these lines should do: https://github.com/flatpak/flatpak/blob/6f86a8ff423a2e7a8e1db70c69612f3fa49ae9d4/common/flatpak-run.c#L2899-L2901
> 
> How do you access the code to remove those lines?

You'd have to build your own flatpak package. This differs a whole lot between distributions.

For Gentoo at least, I can just put a patch file at the right location and it will apply it automatically to every version of `flatpak` that I build.

**Comment by losuler** [comment]
This should now be fixed, now that https://github.com/flatpak/flatpak/pull/5082 has been merged!

**Comment by alaviss** [comment]
Yep, looks like flatpak 1.15.0 will include this fix :tada:

**Comment by Konglomneshued** [comment]
Still have this issue....

![Screenshot from 2022-10-29 13-28-29](https://user-images.githubusercontent.com/94726665/198847303-9069f4ee-ba6f-4229-bee4-e3e8be894674.png)

**Comment by alaviss** [comment]
That's to be expected, the patch fixing this bug has not made it to a stable flatpak release yet.

**Comment by Fabianoshz** [comment]
I'm using 1.15 and I still have this issue
