### ISSUE TITLE
Destination Directory in ~/Games Cannot Be Found

### ISSUE THREAD

**Issue by ghost** [flathub/net.lutris.Lutris#89]
**Describe the problem**
The destination directory, in which the game should be installed, gets deleted after the Rockstar Games launcher or other external game files get downloaded, causing the installation to fail at the later stage of it. 

I have reproduced this issue with Witcher 3: Wild Hunt - Game of the Year Edtion, and Grand Theft Auto 5 using Proton 4.11-12 and Lutris Wine 5.0.

**Is it reproducible with native Lutris?**
No, it is not reproducible. Tested on Fedora 31 Workstation.

**Steps to reproduce**
1. Search Lutris.net for Grand Theft Auto V using the in-app search engine.
2. Select Grand Theft Auto V, and choose `Rockstar Games Launcher` from the list of install scripts.
3. The installation should fail after an unsuccessful attempt to install the game launcher.

**Expected behavior**
The Rockstar Games launcher appears, and the installation proceeds to the next step, where I should be able to log in to my social club account in order to download and install the game.

**Actual behavior**
The directory `grand-theft-auto-v` in `~/Games` gets deleted, and the installation fails with the error:

```
The executable at path /var/home/user/Games/grand-theft-auto-v/drive_c/Program Files/Rockstar Games/Launcher/Launcher.exe can't be found, please check the destination folder.
Some parts of the installation process may have not completed successfully.
```

**Flatpak info**
`flatpak --version`: Flatpak 1.4.3
`flatpak --gl-drivers`: mesa-aco

**Comment by Bryophyllum** [comment]
I am able to reproduce this issue on a fresh Fedora Silverblue 31 installation.

**Comment by RobLoach** [comment]
Interesting... Do you know what permissionwe have to add in to make it work?

**Comment by HarryMichal** [comment]
I just tried to enable unrestricted access to the home folder and the issue was solved. But that is not really desirable, right?

**Comment by Bryophyllum** [comment]
I suspect that the runtime or Flatpak itself are to blame. I downgraded the Lutris Flatpak down to the last known working for me version, yet this issue persisted. 

The default permissions allow this flatpak to create and write to the `Game` directory in the user's home directory. This is, in my understanding, by no means a problem with the permissions per-se.

**Comment by A6GibKm** [comment]
`flatpak install org.gnome.Platform.Compat.i386//3.36` fixes it for me.

**Comment by Bryophyllum** [comment]
@A6GibKm Thank you for sharing you finding. I can confirm that installing the missing runtimes solves this issue.

**Comment by gasinvein** [comment]
So the issue wasn't even caused by the sandbox and it was effectively disabled in f850c202af1818794619063c4e4e351a7acd06c0 for nothing?

**Comment by Bryophyllum** [comment]
Yes, this appears to be the case. When I was troubleshooting the issue I didn't think of a missing dependency as a plausible cause; I downgraded Lutris and GNOME runtimes back to the known working commits, and as I was running out of patience and time, I assumed that it was a Silverblue thing and out of the scope of this project after seeing https://github.com/flathub/net.lutris.Lutris/issues/90.

**Comment by A6GibKm** [comment]
The issue does not suggest in any way that this is not a sandbox issue, no one would think that a Compat extension is missing with a 'file not found' error.

@gasinvein could you add in the README the instruction to install `org.gnome.Platform.Compat.i386//3.36`?

**Comment by gasinvein** [comment]
@A6GibKm 
> The issue does not suggest in any way that this is not a sandbox issue

Maybe you should notify the developers. Lutris was unable to run `wine` during game installation, but it complains only about missing destination directory. This probably shouldn't be this way, maybe catch the error earlier or something.
>could you add in the README

No, I'm not the maintainer anymore.

**Comment by A6GibKm** [comment]
I am closing, since ultimately it turned to be a duplicated of #53.
